### ISSUE TITLE
Bakalárska práca

### ISSUE THREAD

**Issue by Sibyx** [Sibyx/mdns#27]
Rád by som sa chcel venovať tomuto projektu ako bakalárskej práci. Zatiaľ je povedzme v MVP stave ale mám kopec nápadov, ktoré by som chcel s týmto projektom skúsiť a dotlačiť do do prevádzky k skutočným zberateľom hmyzu (zatiaľ mám minimálne jedného a poznám zopár luďí v Múzeu Andreja Kmeťa v Martine - zatiaľ som sa s ním na túto tému nebavil).

Chcel by som sa spýtať, či by sa to dalo spracovať ako bakalárska práca a či by ste to chceli so mnou vôbec riešiť. 

Je tam niekoľko vecí, ktorých by sa dalo chytiť ako napríklad 

- vyriešiť správna reprezentácia entomologických dát (issue #12, aj keď v poslednej dobe som rozmýšľal a skúmal reprezentáciu [ITIS](https://www.itis.gov/) databázy v relčnej forme)
- mohlo by byť zaujímavé pohrať sa so semantickým webom a microdata
- možno čistá utópia, ale dala by sa spraviť platforma, kde by bežala služba spolu s ElasticSearch, ktorá by agregovala dáta so zbierok a vyhľadávala by nad viacerími MDNS inštanciami rozhodených do internetu (niečo ako Google nad viacerími inštanciami projektu - Elastic tam aktuálne nie je len kvôli HW požiadavkám)
- samozrejme je potrebné dokončiť aktuálny katalóg, momentálne je implementovaná skôr jednoduchšia administračná časť

Ďakujem za Váš názor.

**Comment by Sibyx** [comment]
@crutch Super, vdaka. Este pre istotu pridavam mention aby ste nestratili link na novu lokaciu repozitara.

**Comment by crutch** [comment]
Este pre istotu - v AISe je to odovzdane hej?

**Comment by Sibyx** [comment]
Ano samozrejme, 3x odovzdany master + dokumentacia + commit hash
